### ISSUE TITLE
ChebyKAN benchmarks

### ISSUE THREAD

**Issue by iiisak** [Jerry-Master/KAN-benchmarking#1]
ChebyKAN uses Chebyshev polynomials instead of B-splines.
https://github.com/SynodicMonth/ChebyKAN

Would be interesting to see it benchmarked against other KANs

**Comment by Jerry-Master** [comment]
I added it to the benchmark. I chose degree 9 so that the number of parameters is roughly the same. Its performance is between that of efficient kan and fourier kan.
