### ISSUE TITLE
Bump ChebyKAN commit

### ISSUE THREAD

**Issue by iiisak** [Jerry-Master/KAN-benchmarking#3]
ChebyKAN has been optimized in recent commits to use fully vectorized operations and no for-loops.
Would be interesting to see how this speedier version compares to MLP and other KANs

**Comment by Jerry-Master** [comment]
Updated, thanks. That version is comparable to pure pytorch implementation of MLP. So in terms of performance we are almost there. I believed that was possible, but never thought it would take so little.
