### ISSUE TITLE
Add Fast-Kan (KAN-RBF)

### ISSUE THREAD

**Issue by akaashdash** [Jerry-Master/KAN-benchmarking#5]
Recent short paper reviews the relationship between RBF and KAN: https://arxiv.org/abs/2405.06721

The official paper's code is here: https://github.com/ZiyaoLi/fast-kan
A faster forked implementation is here: https://github.com/AthanasiosDelis/faster-kan
An alternative implementation of the original is here: https://github.com/Sid2690/RBF-KAN/blob/main/RBF_KAN.py

Any chance you are able to add these to the benchmark leaderboard?

**Comment by Jerry-Master** [comment]
I don't have access to my CUDA workstation now. When I can I will try to update. Or you can do a pull request if you want.

**Comment by Jerry-Master** [comment]
It is now added. It is the second best implementation in terms of efficiency. The ChebyKAN continues to be the first.
